spring:
  application:
    name: resources-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: resources
      username: root
      password: root
      authentication-database: admin
      uuid-representation: standard

server:
  port: 8084

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: [health, info, env, metrics]