spring:
    application:
        name: resources-service
    data:
        mongodb:
            host: ${MONGODB_HOST:localhost}
            port: ${MONGODB_PORT:27017}
            database: ${MONGODB_DATABASE:resources}
            username: ${MONGODB_USERNAME:root}
            password: ${MONGODB_PASSWORD:root}
            authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}
            uuid-representation: ${MONGODB_UUID_REPRESENTATION:standard}

server:
    port: 8084

springdoc:
    show-actuator: true

management:
    endpoints:
        web:
            exposure:
                include: [health, info, env, metrics]