apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /data/standard/default/mongo-volume
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem