apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongodb
  name: mongodb
  namespace: cs-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
          args: ["--dbpath","/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: pass12345
          image: mongo:latest
          name: mongodb
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data-dir
              mountPath: /data/db
      volumes:
        - name: mongo-data-dir
          persistentVolumeClaim:
            claimName: mongodb-pvc
      restartPolicy: Unless-Stopped
