apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: resources
  name: resources
  namespace: cs-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: resources
  template:
    metadata:
      labels:
        io.kompose.service: resources
    spec:
      containers:
        - env:
            - name: MONGODB_HOST
              value: ${MONGODB_SERVICE_IP}
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: resources
            - name: MONGODB_USERNAME
              value: root
            - name: MONGODB_PASSWORD
              value: root
            - name: MONGODB_AUTHENTICATION_DATABASE
              value: admin
            - name: MONGODB_UUID_REPRESENTATION
              value: standard
            - name: KEYCLOAK_CLIENT_ID
              value: oauth
            - name: KEYCLOAK_CLIENT_SECRET
              value: 04bfUatIDO6ipwg1TF2mTzHrX8UZD02Z
            - name: KEYCLOAK_REALM
              value: construcao-sw
            - name: KEYCLOAK_REALM_URL
              value: http://${KEYCLOAK_SERVICE_IP}:8090
          image: ghcr.io/constr-sw-2023-1/backend-g4:latest
          name: resources
          ports:
            - containerPort: 8084
      imagePullSecrets:
        - name: ghcr-secret
      imagePullPolicy: Always
      restartPolicy: Always
